field.widget.settings.pos_order_item_widget:
  type: mapping
  label: 'Commerce POS Order item widget settings'
  mapping:
    num_results:
      type: integer
      label: 'Number of results to display'
    placeholder:
      type: label
      label: 'Placeholder'
    purchasable_entity_view_mode:
      type: string
      label: 'Purchasable entity view mode'
    size:
      type: integer
      label: 'Size'
commerce_pos.settings:
  type: config_object
  label: 'Commerce POS config settings'
  mapping:
    order_lookup_limit:
      type: integer
      label: 'Commerce POS order lookup limit'
    order_lookup_like_search:
      type: boolean
      label: 'Commerce POS order lookup search using "like"'
commerce_order.commerce_order_item_type.return.third_party.commerce_tax:
  type: mapping
  label: 'Tax settings'
  mapping:
    taxable_type:
      type: string
      label: 'Taxable type'
